-- 코드를 입력하세요
SELECT P.PRODUCT_CODE,
       SUM(P.PRICE*S.SALES_AMOUNT) AS SALES
FROM PRODUCT P inner join OFFLINE_SALE S on P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, P.PRODUCT_CODE