SELECT A.WRITER_ID AS USER_ID, B.NICKNAME, 
CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소, 
CONCAT(
        SUBSTR(TLNO,1,3), '-', 
        SUBSTR(TLNO,4,4), '-', 
        SUBSTR(TLNO,8,4)
    ) AS 전화번호
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B ON A.WRITER_ID = B.USER_ID
GROUP BY A.WRITER_ID, 전체주소, 전화번호
HAVING COUNT(*) >= 3 -- 중고거래 게시물을 3건 이상 등록한 사용자
ORDER BY USER_ID DESC;